name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  firebase_storage:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core
  file_picker: ^1.13.3


dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_storage:
    path: ../
  firebase_storage_platform_interface:
    path: ../../firebase_storage_platform_interface

dev_dependencies:
  pedantic: ^1.8.0
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/hello.txt

environment:
  sdk: ">=2.3.0 <3.0.0"
