name: cloud_functions_web
description: The web implementation of cloud_functions
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions_web
version: 3.0.0-dev.2

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFunctionsWeb
        fileName: cloud_functions_web.dart

dependencies:
  firebase_core: ^0.5.0+1
  cloud_functions_platform_interface: ^3.0.0-dev.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^7.0.0
  http_parser: ^3.1.3
  meta: ^1.1.7

dev_dependencies:
  firebase_core_web: ^0.2.0
  firebase_core_platform_interface: ^2.0.0
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  js: ^0.6.0

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

